version: '3.8'

services:
  betfair:
    build: .
    container_name: betfair_trading_platform
    environment:
      - APP_KEY=${APP_KEY}
      - SESSION_TOKEN=${SESSION_TOKEN}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    depends_on:
      - kafka
    networks:
      - betfair_network

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - betfair_network

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - betfair_network

  airflow:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow
    environment:
      - LOAD_EX=y
      - EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    depends_on:
      - betfair
    networks:
      - betfair_network

networks:
  betfair_network:
    driver: bridge